SELECT * FROM HR.EMPLOYEES;

SELECT COUNT(*) FROM HR.EMPLOYEES;

SELECT COUNT(NVL(COMMISSION_PCT, 0)) FROM HR.EMPLOYEES;

SELECT COUNT(DISTINCT COMMISSION_PCT), COUNT(HIRE_DATE) FROM HR.EMPLOYEES;

DESC HR.EMPLOYEES;

/* Experimento 1 */
SELECT COUNT(*), COUNT(DISTINCT DEPARTMENT_ID), COUNT (DISTINCT JOB_ID) FROM HR.EMPLOYEES;

Select avg(2) from hr.employees; 

Select round(avg(salary), 2) from hr.employees;

Select avg(distinct salary) from hr.employees;

Select avg(nvl(commission_pct,0)) from hr.employees;

-- EXPERIMENTO 2 --

SELECT AVG((SYSDATE - HIRE_DATE)/365)
FROM HR.EMPLOYEES
WHERE JOB_ID LIKE 'IT_PROG';

SELECT SUM(DISTINCT SALARY) FROM HR.EMPLOYEES;

SELECT SUM(SYSDATE-HIRE_DATE)
FROM HR.EMPLOYEES;

Select min(commission_pct), max(commission_pct) from hr.employees; 

Select min(start_date), max(end_date) from hr.JOB_HISTORY;  

Select min(job_id), max(job_id) from hr.employees; 

DESC HR.JOB_HISTORY

--EXPERIMENTO 4--
SELECT MIN(HIRE_DATE), MIN (SALARY), MAX(HIRE_DATE), MAX(SALARY)
FROM HR.EMPLOYEES
WHERE JOB_ID LIKE 'SA_REP';

SELECT JOB_ID, DEPARTMENT_ID, SUM(SALARY)
FROM HR.EMPLOYEES
GROUP BY JOB_ID,DEPARTMENT_ID;

-- EL WHERE VA ANTES SIEMPRE QUE EL GROUP BY --
SELECT JOB_ID, DEPARTMENT_ID, SUM(SALARY)
FROM HR.EMPLOYEES
GROUP BY JOB_ID,DEPARTMENT_ID
HAVING DEPARTMENT_ID > 40 AND SUM(SALARY) > 50000;


-- EXPERIMENTO 6 --

select end_date, count(*)
from hr.job_history
GROUP BY END_DATE;

select END_DATE, START_DATE, count(*)
from hr.job_history
group by END_DATE, START_DATE;


